# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    paths-ignore:
      - 'images/**'
      - README.md
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [ created ]
  workflow_call:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  secondjob:
    name: Second Job  
    uses: shb-consulting/gh_workflow/.github/workflows/blank.yml@main
 
