# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_call:
    secrets:
      SOME_SECRET:
        required: true
  push:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  secondjob:
    name: Second Job  
    uses: shb-consulting/gh_workflow/.github/workflows/blank.yml@main
 
